import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import './index.css';
import outputs from '../amplify_outputs.json';

// Configure Amplify using amplify_outputs.json generated by backend build
// This ensures frontend uses the same AppSync API that the backend deploys to
// The backend build (ampx pipeline-deploy) generates this file with the correct API endpoint
const config = {
  ...outputs,
  auth: {
    ...outputs.auth,
    // Ensure Cognito User Pool is configured
    Cognito: {
      userPoolId: outputs.auth.user_pool_id,
      userPoolClientId: outputs.auth.user_pool_client_id,
      identityPoolId: outputs.auth.identity_pool_id,
    },
  },
  data: {
    ...outputs.data,
    // Use the API endpoint from amplify_outputs.json (generated by backend)
    // Do NOT hardcode - let the backend build determine the correct API
    api_key: null, // Use Cognito User Pools, not API_KEY
    // Explicitly set authorization mode
    defaultAuthMode: 'userPool',
  },
};

Amplify.configure(config);

// Log the configured API endpoint for debugging
console.log('[Amplify Config] AppSync API URL:', config.data?.url);
console.log('[Amplify Config] AppSync API ID:', config.data?.url?.match(/https:\/\/([^.]+)\.appsync-api/)?.[1]);

// Load debug utilities after Amplify is configured (they use generateClient/Data)
import('./utils/flightStatusDebug');
import('./utils/recurringTripsDebug');
import('./utils/deleteAllTrips');

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);
